// <auto-generated />
namespace RestaurantReview.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201502031302568_changemodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
